version: '2'
services:
    medusatattoo-app:
        image: medusatattoo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://medusatattoo-mysql:3306/medusatattoo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    medusatattoo-mysql:
        extends:
            file: mysql.yml
            service: medusatattoo-mysql
